# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Dynamic_Dataset": "09_utils.ipynb",
         "Processing_Dataset": "09_utils.ipynb",
         "Embeddings": "09_utils.ipynb",
         "englishStemmer": "09_utils.ipynb",
         "__read_dataset": "10_preprocessing.ipynb",
         "__train_test_split": "10_preprocessing.ipynb",
         "__create_corpora": "10_preprocessing.ipynb",
         "get_training_corpora": "10_preprocessing.ipynb",
         "process_corpora": "10_preprocessing.ipynb",
         "show_loss_accurracy_plots": "model_evaluation.ipynb",
         "evaluate_model": "model_evaluation.ipynb",
         "load_securereqnet_model": "models.ipynb",
         "create_alpha": "models.ipynb",
         "fit_model": "models.ipynb"}

modules = ["core.py",
           "utils.py",
           "preprocessing.py",
           "model_evaluation.py",
           "models.py"]

doc_url = "https://rmclanton.github.io/SecureReqNet/"

git_url = "https://github.com/rmclanton/SecureReqNet"

def custom_doc_links(name): return None
