# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'unexported', 'use_unexported']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
#export

def unexported():
    print("Success")

# Cell
def use_unexported():
    unexported()


# Cell
say_hello("TEST")